// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XuLyKhoaLuan.Data;

#nullable disable

namespace XuLyKhoaLuan.Migrations
{
    [DbContext(typeof(XuLyKhoaLuanContext))]
    partial class XuLyKhoaLuanContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DetaiChuyennganh", b =>
                {
                    b.Property<string>("MaCn")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaCN");

                    b.Property<string>("MaDt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaDT");

                    b.HasKey("MaCn", "MaDt");

                    b.HasIndex("MaDt");

                    b.ToTable("DETAI_CHUYENNGANH", (string)null);
                });

            modelBuilder.Entity("Rade", b =>
                {
                    b.Property<string>("MaGv")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaGV");

                    b.Property<string>("MaDt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaDT");

                    b.HasKey("MaGv", "MaDt");

                    b.HasIndex("MaDt");

                    b.ToTable("RADE", (string)null);
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Baocao", b =>
                {
                    b.Property<string>("MaCv")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaCV");

                    b.Property<string>("MaSv")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaSV");

                    b.Property<string>("NamHoc")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Dot")
                        .HasColumnType("int");

                    b.Property<int>("LanNop")
                        .HasColumnType("int");

                    b.Property<string>("FileBc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("File_BC");

                    b.Property<DateTime?>("ThoiGianNop")
                        .HasColumnType("datetime");

                    b.HasKey("MaCv", "MaSv", "NamHoc", "Dot", "LanNop");

                    b.HasIndex("MaSv", "NamHoc", "Dot");

                    b.ToTable("BAOCAO", (string)null);
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Binhluan", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int?>("Dot")
                        .HasColumnType("int");

                    b.Property<string>("MaCv")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaCV");

                    b.Property<string>("MaSv")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaSV");

                    b.Property<string>("NamHoc")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NoiDung")
                        .HasColumnType("ntext");

                    b.Property<DateTime?>("ThoiGian")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("MaCv");

                    b.HasIndex("MaSv", "NamHoc", "Dot");

                    b.ToTable("BINHLUAN", (string)null);
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Bomon", b =>
                {
                    b.Property<string>("MaBm")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaBM");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MaKhoa")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenBm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenBM");

                    b.HasKey("MaBm");

                    b.HasIndex("MaKhoa");

                    b.ToTable("BOMON", (string)null);
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Chuyennganh", b =>
                {
                    b.Property<string>("MaCn")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaCN");

                    b.Property<string>("MaKhoa")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TenCn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("TenCN");

                    b.HasKey("MaCn");

                    b.HasIndex("MaKhoa");

                    b.ToTable("CHUYENNGANH", (string)null);
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Congviec", b =>
                {
                    b.Property<string>("MaCv")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaCV");

                    b.Property<DateTime?>("HanChot")
                        .HasColumnType("datetime");

                    b.Property<string>("MaDt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaDT");

                    b.Property<string>("MaGv")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaGV");

                    b.Property<int?>("MaNhom")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("ntext");

                    b.Property<double?>("MucDoHoanThanh")
                        .HasColumnType("float");

                    b.Property<string>("TenCv")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenCV");

                    b.Property<string>("YeuCau")
                        .HasColumnType("ntext");

                    b.HasKey("MaCv");

                    b.HasIndex("MaNhom");

                    b.HasIndex("MaGv", "MaDt");

                    b.ToTable("CONGVIEC", (string)null);
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Dangky", b =>
                {
                    b.Property<int>("MaNhom")
                        .HasColumnType("int");

                    b.Property<string>("MaDt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaDT");

                    b.Property<DateTime?>("NgayBd")
                        .HasColumnType("date")
                        .HasColumnName("NgayBD");

                    b.Property<DateTime>("NgayDk")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayDK");

                    b.Property<DateTime?>("NgayGiao")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayKt")
                        .HasColumnType("date")
                        .HasColumnName("NgayKT");

                    b.HasKey("MaNhom", "MaDt");

                    b.HasIndex("MaDt");

                    b.ToTable("DANGKY", (string)null);
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Detai", b =>
                {
                    b.Property<string>("MaDt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaDT");

                    b.Property<int?>("Slmax")
                        .HasColumnType("int")
                        .HasColumnName("SLMax");

                    b.Property<int?>("Slmin")
                        .HasColumnType("int")
                        .HasColumnName("SLMin");

                    b.Property<string>("TenDt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenDT");

                    b.Property<string>("TomTat")
                        .HasColumnType("ntext");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaDt");

                    b.ToTable("DETAI", (string)null);
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Dotdk", b =>
                {
                    b.Property<string>("NamHoc")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Dot")
                        .HasColumnType("int");

                    b.HasKey("NamHoc", "Dot");

                    b.ToTable("DOTDK", (string)null);
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Duyetdt", b =>
                {
                    b.Property<string>("MaGv")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaGV");

                    b.Property<string>("MaDt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaDT");

                    b.Property<int>("LanDuyet")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDuyet")
                        .HasColumnType("datetime");

                    b.Property<string>("NhanXet")
                        .HasColumnType("ntext");

                    b.HasKey("MaGv", "MaDt", "LanDuyet");

                    b.HasIndex("MaDt");

                    b.ToTable("DUYETDT", (string)null);
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Giangvien", b =>
                {
                    b.Property<string>("MaGv")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaGV");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("HocHam")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HocVi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaBm")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaBM");

                    b.Property<DateTime?>("NgayNghi")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayNhanViec")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenGv")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("TenGV");

                    b.HasKey("MaGv");

                    b.HasIndex("MaBm");

                    b.ToTable("GIANGVIEN", (string)null);
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Giaovu", b =>
                {
                    b.Property<string>("MaGv")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaGV");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("MaKhoa")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime?>("NgayNghi")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayNhanViec")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenGv")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("TenGV");

                    b.HasKey("MaGv");

                    b.HasIndex("MaKhoa");

                    b.ToTable("GIAOVU", (string)null);
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Hdcham", b =>
                {
                    b.Property<string>("MaGv")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaGV");

                    b.Property<string>("MaDt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaDT");

                    b.Property<double?>("Diem")
                        .HasColumnType("float");

                    b.Property<int>("Dot")
                        .HasColumnType("int");

                    b.Property<double?>("HeSo")
                        .HasColumnType("float");

                    b.Property<string>("MaSv")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaSV");

                    b.Property<string>("NamHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("MaGv", "MaDt");

                    b.HasIndex("MaSv", "NamHoc", "Dot");

                    b.ToTable("HDCHAM", (string)null);
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Hdgopy", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("MaCv")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaCV");

                    b.Property<string>("MaDt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaDT");

                    b.Property<string>("MaGv")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaGV");

                    b.Property<string>("NoiDung")
                        .HasColumnType("ntext");

                    b.Property<DateTime?>("ThoiGian")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("MaCv");

                    b.HasIndex("MaGv", "MaDt");

                    b.ToTable("HDGOPY", (string)null);
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Hdpbcham", b =>
                {
                    b.Property<string>("MaGv")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaGV");

                    b.Property<string>("MaHd")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaHD");

                    b.Property<string>("MaDt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaDT");

                    b.Property<string>("MaSv")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaSV");

                    b.Property<string>("NamHoc")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Dot")
                        .HasColumnType("int");

                    b.Property<double?>("Diem")
                        .HasColumnType("float");

                    b.Property<double?>("HeSo")
                        .HasColumnType("float");

                    b.HasKey("MaGv", "MaHd", "MaDt", "MaSv", "NamHoc", "Dot");

                    b.HasIndex("MaSv", "NamHoc", "Dot");

                    b.ToTable("HDPBCHAM", (string)null);
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Hdpbnhanxet", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("MaDt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaDT");

                    b.Property<string>("MaGv")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaGV");

                    b.Property<string>("MaHd")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaHD");

                    b.Property<string>("NoiDung")
                        .HasColumnType("ntext");

                    b.Property<DateTime?>("ThoiGian")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("MaGv", "MaHd", "MaDt");

                    b.ToTable("HDPBNHANXET", (string)null);
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Hdphanbien", b =>
                {
                    b.Property<string>("MaGv")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaGV");

                    b.Property<string>("MaHd")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaHD");

                    b.Property<string>("MaDt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaDT");

                    b.Property<double?>("Diem")
                        .HasColumnType("float");

                    b.HasKey("MaGv", "MaHd", "MaDt")
                        .HasName("PK_CHAMDIEM");

                    b.HasIndex("MaDt");

                    b.HasIndex("MaHd", "MaGv");

                    b.ToTable("HDPHANBIEN", (string)null);
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Hoidong", b =>
                {
                    b.Property<string>("MaHd")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaHD");

                    b.Property<string>("DiaDiem")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaBm")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaBM");

                    b.Property<DateTime?>("NgayBaoVe")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayLap")
                        .HasColumnType("date");

                    b.Property<string>("TenHd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenHD");

                    b.HasKey("MaHd");

                    b.HasIndex("MaBm");

                    b.ToTable("HOIDONG", (string)null);
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Huongdan", b =>
                {
                    b.Property<string>("MaGv")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaGV");

                    b.Property<string>("MaDt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaDT");

                    b.Property<bool?>("DuaRaHd")
                        .HasColumnType("bit")
                        .HasColumnName("DuaRaHD");

                    b.HasKey("MaGv", "MaDt");

                    b.HasIndex("MaDt");

                    b.ToTable("HUONGDAN", (string)null);
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Kehoach", b =>
                {
                    b.Property<int>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<string>("FileKh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FileKH");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MaBm")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaBM");

                    b.Property<string>("MaKhoa")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("SoLuongDt")
                        .HasColumnType("int")
                        .HasColumnName("SoLuongDT");

                    b.Property<string>("TenKh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenKH");

                    b.Property<DateTime?>("ThoiGianBd")
                        .HasColumnType("datetime")
                        .HasColumnName("ThoiGianBD");

                    b.Property<DateTime?>("ThoiGianKt")
                        .HasColumnType("datetime")
                        .HasColumnName("ThoiGianKT");

                    b.HasKey("MaKh");

                    b.HasIndex("MaBm");

                    b.HasIndex("MaKhoa");

                    b.ToTable("KEHOACH", (string)null);
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Khoa", b =>
                {
                    b.Property<string>("MaKhoa")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phong")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKhoa");

                    b.ToTable("KHOA", (string)null);
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Loimoi", b =>
                {
                    b.Property<string>("MaSv")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaSV");

                    b.Property<string>("NamHoc")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Dot")
                        .HasColumnType("int");

                    b.Property<int>("MaNhom")
                        .HasColumnType("int");

                    b.Property<string>("LoiNhan")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime?>("ThoiGian")
                        .HasColumnType("datetime");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaSv", "NamHoc", "Dot", "MaNhom");

                    b.HasIndex("MaNhom");

                    b.ToTable("LOIMOI", (string)null);
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Nhiemvu", b =>
                {
                    b.Property<int>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.Property<string>("FileNv")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FileNV");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MaBm")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaBM");

                    b.Property<string>("MaGv")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaGV");

                    b.Property<int>("SoLuongDt")
                        .HasColumnType("int")
                        .HasColumnName("SoLuongDT");

                    b.Property<string>("TenNv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenNV");

                    b.Property<DateTime?>("ThoiGianBd")
                        .HasColumnType("datetime")
                        .HasColumnName("ThoiGianBD");

                    b.Property<DateTime?>("ThoiGianKt")
                        .HasColumnType("datetime")
                        .HasColumnName("ThoiGianKT");

                    b.HasKey("MaNv");

                    b.HasIndex("MaBm");

                    b.HasIndex("MaGv");

                    b.ToTable("NHIEMVU", (string)null);
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Nhom", b =>
                {
                    b.Property<int>("MaNhom")
                        .HasColumnType("int");

                    b.Property<int?>("Slmax")
                        .HasColumnType("int")
                        .HasColumnName("SLMax");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TruongNhom")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("MaNhom");

                    b.HasIndex("TruongNhom");

                    b.ToTable("NHOM", (string)null);
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Pbcham", b =>
                {
                    b.Property<string>("MaGv")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaGV");

                    b.Property<string>("MaDt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaDT");

                    b.Property<double?>("Diem")
                        .HasColumnType("float");

                    b.Property<int>("Dot")
                        .HasColumnType("int");

                    b.Property<string>("MaSv")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaSV");

                    b.Property<string>("NamHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("MaGv", "MaDt");

                    b.HasIndex("MaSv", "NamHoc", "Dot");

                    b.ToTable("PBCHAM", (string)null);
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Pbnhanxet", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("MaDt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaDT");

                    b.Property<string>("MaGv")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaGV");

                    b.Property<string>("NoiDung")
                        .HasColumnType("ntext");

                    b.Property<DateTime?>("ThoiGian")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("MaGv", "MaDt");

                    b.ToTable("PBNHANXET", (string)null);
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Phanbien", b =>
                {
                    b.Property<string>("MaGv")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaGV");

                    b.Property<string>("MaDt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaDT");

                    b.Property<bool?>("DuaRaHd")
                        .HasColumnType("bit")
                        .HasColumnName("DuaRaHD");

                    b.HasKey("MaGv", "MaDt");

                    b.HasIndex("MaDt");

                    b.ToTable("PHANBIEN", (string)null);
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Sinhvien", b =>
                {
                    b.Property<string>("MaSv")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaSV");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Lop")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaCn")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaCN");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenSv")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("TenSV");

                    b.HasKey("MaSv");

                    b.HasIndex("MaCn");

                    b.ToTable("SINHVIEN", (string)null);
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Thamgia", b =>
                {
                    b.Property<string>("MaSv")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaSV");

                    b.Property<string>("NamHoc")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Dot")
                        .HasColumnType("int");

                    b.Property<double?>("DiemTb")
                        .HasColumnType("float")
                        .HasColumnName("DiemTB");

                    b.Property<int?>("MaNhom")
                        .HasColumnType("int");

                    b.HasKey("MaSv", "NamHoc", "Dot");

                    b.HasIndex("NamHoc", "Dot");

                    b.ToTable("THAMGIA", (string)null);
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Thamgiahd", b =>
                {
                    b.Property<string>("MaHd")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaHD");

                    b.Property<string>("MaGv")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaGV");

                    b.Property<string>("MaVt")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaVT");

                    b.HasKey("MaHd", "MaGv");

                    b.HasIndex("MaGv");

                    b.HasIndex("MaVt");

                    b.ToTable("THAMGIAHD", (string)null);
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Thongbao", b =>
                {
                    b.Property<int>("MaTb")
                        .HasColumnType("int")
                        .HasColumnName("MaTB");

                    b.Property<string>("FileTb")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FileTB");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaKhoa")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("MoTa")
                        .HasColumnType("ntext");

                    b.Property<string>("NoiDung")
                        .HasColumnType("ntext");

                    b.Property<string>("TenTb")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenTB");

                    b.HasKey("MaTb");

                    b.HasIndex("MaKhoa");

                    b.ToTable("THONGBAO", (string)null);
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Truongbm", b =>
                {
                    b.Property<string>("MaBm")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaBM");

                    b.Property<string>("MaGv")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaGV");

                    b.Property<DateTime?>("NgayNghi")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayNhanChuc")
                        .HasColumnType("date");

                    b.HasKey("MaBm", "MaGv");

                    b.HasIndex("MaGv");

                    b.ToTable("TRUONGBM", (string)null);
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Truongkhoa", b =>
                {
                    b.Property<string>("MaKhoa")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("MaGv")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaGV");

                    b.Property<DateTime?>("NgayNghi")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayNhanChuc")
                        .HasColumnType("date");

                    b.HasKey("MaKhoa", "MaGv");

                    b.HasIndex("MaGv");

                    b.ToTable("TRUONGKHOA", (string)null);
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Vaitro", b =>
                {
                    b.Property<string>("MaVt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaVT");

                    b.Property<string>("TenVaiTro")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaVt");

                    b.ToTable("VAITRO", (string)null);
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Xacnhan", b =>
                {
                    b.Property<string>("MaGv")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaGV");

                    b.Property<string>("MaDt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MaDT");

                    b.Property<bool?>("DuaRaHd")
                        .HasColumnType("bit")
                        .HasColumnName("DuaRaHD");

                    b.HasKey("MaGv", "MaDt");

                    b.HasIndex("MaDt");

                    b.ToTable("XACNHAN", (string)null);
                });

            modelBuilder.Entity("DetaiChuyennganh", b =>
                {
                    b.HasOne("XuLyKhoaLuan.Data.Chuyennganh", null)
                        .WithMany()
                        .HasForeignKey("MaCn")
                        .IsRequired()
                        .HasConstraintName("FK_DT_CN_CHUYENNGANH");

                    b.HasOne("XuLyKhoaLuan.Data.Detai", null)
                        .WithMany()
                        .HasForeignKey("MaDt")
                        .IsRequired()
                        .HasConstraintName("FK_DT_CN_DETAI");
                });

            modelBuilder.Entity("Rade", b =>
                {
                    b.HasOne("XuLyKhoaLuan.Data.Detai", null)
                        .WithMany()
                        .HasForeignKey("MaDt")
                        .IsRequired()
                        .HasConstraintName("FK_RADE_DETAI");

                    b.HasOne("XuLyKhoaLuan.Data.Giangvien", null)
                        .WithMany()
                        .HasForeignKey("MaGv")
                        .IsRequired()
                        .HasConstraintName("FK_RADE_GIANGVIEN");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Baocao", b =>
                {
                    b.HasOne("XuLyKhoaLuan.Data.Congviec", "MaCvNavigation")
                        .WithMany("Baocaos")
                        .HasForeignKey("MaCv")
                        .IsRequired()
                        .HasConstraintName("FK_BAOCAO_CONGVIEC");

                    b.HasOne("XuLyKhoaLuan.Data.Thamgia", "Thamgium")
                        .WithMany("Baocaos")
                        .HasForeignKey("MaSv", "NamHoc", "Dot")
                        .IsRequired()
                        .HasConstraintName("FK_BAOCAO_THAMGIA");

                    b.Navigation("MaCvNavigation");

                    b.Navigation("Thamgium");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Binhluan", b =>
                {
                    b.HasOne("XuLyKhoaLuan.Data.Congviec", "MaCvNavigation")
                        .WithMany("Binhluans")
                        .HasForeignKey("MaCv")
                        .HasConstraintName("FK_BINHLUAN_CONGVIEC");

                    b.HasOne("XuLyKhoaLuan.Data.Thamgia", "Thamgium")
                        .WithMany("Binhluans")
                        .HasForeignKey("MaSv", "NamHoc", "Dot")
                        .HasConstraintName("FK_BINHLUAN_THAMGIA");

                    b.Navigation("MaCvNavigation");

                    b.Navigation("Thamgium");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Bomon", b =>
                {
                    b.HasOne("XuLyKhoaLuan.Data.Khoa", "MaKhoaNavigation")
                        .WithMany("Bomons")
                        .HasForeignKey("MaKhoa")
                        .HasConstraintName("FK_BOMON_KHOA");

                    b.Navigation("MaKhoaNavigation");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Chuyennganh", b =>
                {
                    b.HasOne("XuLyKhoaLuan.Data.Khoa", "MaKhoaNavigation")
                        .WithMany("Chuyennganhs")
                        .HasForeignKey("MaKhoa")
                        .HasConstraintName("FK_CHUYENNGANH_KHOA");

                    b.Navigation("MaKhoaNavigation");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Congviec", b =>
                {
                    b.HasOne("XuLyKhoaLuan.Data.Nhom", "MaNhomNavigation")
                        .WithMany("Congviecs")
                        .HasForeignKey("MaNhom")
                        .HasConstraintName("FK_CONGVIEC_NHOM");

                    b.HasOne("XuLyKhoaLuan.Data.Huongdan", "Ma")
                        .WithMany("Congviecs")
                        .HasForeignKey("MaGv", "MaDt")
                        .HasConstraintName("FK_CONGVIEC_HUONGDAN");

                    b.Navigation("Ma");

                    b.Navigation("MaNhomNavigation");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Dangky", b =>
                {
                    b.HasOne("XuLyKhoaLuan.Data.Detai", "MaDtNavigation")
                        .WithMany("Dangkies")
                        .HasForeignKey("MaDt")
                        .IsRequired()
                        .HasConstraintName("FK_DANGKY_DETAI");

                    b.HasOne("XuLyKhoaLuan.Data.Nhom", "MaNhomNavigation")
                        .WithMany("Dangkies")
                        .HasForeignKey("MaNhom")
                        .IsRequired()
                        .HasConstraintName("FK_DANGKY_NHOM");

                    b.Navigation("MaDtNavigation");

                    b.Navigation("MaNhomNavigation");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Duyetdt", b =>
                {
                    b.HasOne("XuLyKhoaLuan.Data.Detai", "MaDtNavigation")
                        .WithMany("Duyetdts")
                        .HasForeignKey("MaDt")
                        .IsRequired()
                        .HasConstraintName("FK_DUYETDT_DETAI");

                    b.HasOne("XuLyKhoaLuan.Data.Giangvien", "MaGvNavigation")
                        .WithMany("Duyetdts")
                        .HasForeignKey("MaGv")
                        .IsRequired()
                        .HasConstraintName("FK_DUYETDT_GIANGVIEN");

                    b.Navigation("MaDtNavigation");

                    b.Navigation("MaGvNavigation");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Giangvien", b =>
                {
                    b.HasOne("XuLyKhoaLuan.Data.Bomon", "MaBmNavigation")
                        .WithMany("Giangviens")
                        .HasForeignKey("MaBm")
                        .HasConstraintName("FK_GIANGVIEN_BOMON");

                    b.Navigation("MaBmNavigation");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Giaovu", b =>
                {
                    b.HasOne("XuLyKhoaLuan.Data.Khoa", "MaKhoaNavigation")
                        .WithMany("Giaovus")
                        .HasForeignKey("MaKhoa")
                        .HasConstraintName("FK_GIAOVU_KHOA");

                    b.Navigation("MaKhoaNavigation");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Hdcham", b =>
                {
                    b.HasOne("XuLyKhoaLuan.Data.Huongdan", "Ma")
                        .WithOne("Hdcham")
                        .HasForeignKey("XuLyKhoaLuan.Data.Hdcham", "MaGv", "MaDt")
                        .IsRequired()
                        .HasConstraintName("FK_HDCHAM_HUONGDAN");

                    b.HasOne("XuLyKhoaLuan.Data.Thamgia", "Thamgium")
                        .WithMany("Hdchams")
                        .HasForeignKey("MaSv", "NamHoc", "Dot")
                        .IsRequired()
                        .HasConstraintName("FK_HDCHAM_THAMGIA");

                    b.Navigation("Ma");

                    b.Navigation("Thamgium");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Hdgopy", b =>
                {
                    b.HasOne("XuLyKhoaLuan.Data.Congviec", "MaCvNavigation")
                        .WithMany("Hdgopies")
                        .HasForeignKey("MaCv")
                        .HasConstraintName("FK_HDGOPY_CONGVIEC");

                    b.HasOne("XuLyKhoaLuan.Data.Huongdan", "Ma")
                        .WithMany("Hdgopies")
                        .HasForeignKey("MaGv", "MaDt")
                        .HasConstraintName("FK_HDGOPY_HUONGDAN");

                    b.Navigation("Ma");

                    b.Navigation("MaCvNavigation");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Hdpbcham", b =>
                {
                    b.HasOne("XuLyKhoaLuan.Data.Hdphanbien", "Ma")
                        .WithMany("Hdpbchams")
                        .HasForeignKey("MaGv", "MaHd", "MaDt")
                        .IsRequired()
                        .HasConstraintName("FK_HDPBCHAM_HDPHANBIEN");

                    b.HasOne("XuLyKhoaLuan.Data.Thamgia", "Thamgium")
                        .WithMany("Hdpbchams")
                        .HasForeignKey("MaSv", "NamHoc", "Dot")
                        .IsRequired()
                        .HasConstraintName("FK_HDPBCHAM_THAMGIA");

                    b.Navigation("Ma");

                    b.Navigation("Thamgium");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Hdpbnhanxet", b =>
                {
                    b.HasOne("XuLyKhoaLuan.Data.Hdphanbien", "Ma")
                        .WithMany("Hdpbnhanxets")
                        .HasForeignKey("MaGv", "MaHd", "MaDt")
                        .HasConstraintName("FK_HDPBNHANXET_HDPHANBIEN");

                    b.Navigation("Ma");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Hdphanbien", b =>
                {
                    b.HasOne("XuLyKhoaLuan.Data.Detai", "MaDtNavigation")
                        .WithMany("Hdphanbiens")
                        .HasForeignKey("MaDt")
                        .IsRequired()
                        .HasConstraintName("FK_HDPHANBIEN_DETAI");

                    b.HasOne("XuLyKhoaLuan.Data.Thamgiahd", "Ma")
                        .WithMany("Hdphanbiens")
                        .HasForeignKey("MaHd", "MaGv")
                        .IsRequired()
                        .HasConstraintName("FK_HDPHANBIEN_THAMGIAHD");

                    b.Navigation("Ma");

                    b.Navigation("MaDtNavigation");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Hoidong", b =>
                {
                    b.HasOne("XuLyKhoaLuan.Data.Bomon", "MaBmNavigation")
                        .WithMany("Hoidongs")
                        .HasForeignKey("MaBm")
                        .HasConstraintName("FK_HOIDONG_BOMON");

                    b.Navigation("MaBmNavigation");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Huongdan", b =>
                {
                    b.HasOne("XuLyKhoaLuan.Data.Detai", "MaDtNavigation")
                        .WithMany("Huongdans")
                        .HasForeignKey("MaDt")
                        .IsRequired()
                        .HasConstraintName("FK_HUONGDAN_DETAI");

                    b.HasOne("XuLyKhoaLuan.Data.Giangvien", "MaGvNavigation")
                        .WithMany("Huongdans")
                        .HasForeignKey("MaGv")
                        .IsRequired()
                        .HasConstraintName("FK_HUONGDAN_GIANGVIEN");

                    b.Navigation("MaDtNavigation");

                    b.Navigation("MaGvNavigation");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Kehoach", b =>
                {
                    b.HasOne("XuLyKhoaLuan.Data.Bomon", "MaBmNavigation")
                        .WithMany("Kehoaches")
                        .HasForeignKey("MaBm")
                        .HasConstraintName("FK_KEHOACH_BOMON");

                    b.HasOne("XuLyKhoaLuan.Data.Khoa", "MaKhoaNavigation")
                        .WithMany("Kehoaches")
                        .HasForeignKey("MaKhoa")
                        .HasConstraintName("FK_KEHOACH_KHOA");

                    b.Navigation("MaBmNavigation");

                    b.Navigation("MaKhoaNavigation");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Loimoi", b =>
                {
                    b.HasOne("XuLyKhoaLuan.Data.Nhom", "MaNhomNavigation")
                        .WithMany("Loimois")
                        .HasForeignKey("MaNhom")
                        .IsRequired()
                        .HasConstraintName("FK_LOIMOI_NHOM");

                    b.HasOne("XuLyKhoaLuan.Data.Thamgia", "Thamgium")
                        .WithMany("Loimois")
                        .HasForeignKey("MaSv", "NamHoc", "Dot")
                        .IsRequired()
                        .HasConstraintName("FK_LOIMOI_THAMGIA");

                    b.Navigation("MaNhomNavigation");

                    b.Navigation("Thamgium");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Nhiemvu", b =>
                {
                    b.HasOne("XuLyKhoaLuan.Data.Bomon", "MaBmNavigation")
                        .WithMany("Nhiemvus")
                        .HasForeignKey("MaBm")
                        .HasConstraintName("FK_NHIEMVU_BOMON");

                    b.HasOne("XuLyKhoaLuan.Data.Giangvien", "MaGvNavigation")
                        .WithMany("Nhiemvus")
                        .HasForeignKey("MaGv")
                        .HasConstraintName("FK_NHIEMVU_GIANGVIEN");

                    b.Navigation("MaBmNavigation");

                    b.Navigation("MaGvNavigation");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Nhom", b =>
                {
                    b.HasOne("XuLyKhoaLuan.Data.Sinhvien", "TruongNhomNavigation")
                        .WithMany("Nhoms")
                        .HasForeignKey("TruongNhom")
                        .IsRequired()
                        .HasConstraintName("FK_NHOM_SINHVIEN");

                    b.Navigation("TruongNhomNavigation");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Pbcham", b =>
                {
                    b.HasOne("XuLyKhoaLuan.Data.Phanbien", "Ma")
                        .WithOne("Pbcham")
                        .HasForeignKey("XuLyKhoaLuan.Data.Pbcham", "MaGv", "MaDt")
                        .IsRequired()
                        .HasConstraintName("FK_PBCHAM_PHANBIEN");

                    b.HasOne("XuLyKhoaLuan.Data.Thamgia", "Thamgium")
                        .WithMany("Pbchams")
                        .HasForeignKey("MaSv", "NamHoc", "Dot")
                        .IsRequired()
                        .HasConstraintName("FK_PBCHAM_THAMGIA");

                    b.Navigation("Ma");

                    b.Navigation("Thamgium");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Pbnhanxet", b =>
                {
                    b.HasOne("XuLyKhoaLuan.Data.Phanbien", "Ma")
                        .WithMany("Pbnhanxets")
                        .HasForeignKey("MaGv", "MaDt")
                        .HasConstraintName("FK_PBNHANXET_PHANBIEN");

                    b.Navigation("Ma");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Phanbien", b =>
                {
                    b.HasOne("XuLyKhoaLuan.Data.Detai", "MaDtNavigation")
                        .WithMany("Phanbiens")
                        .HasForeignKey("MaDt")
                        .IsRequired()
                        .HasConstraintName("FK_PHANBIEN_DETAI");

                    b.HasOne("XuLyKhoaLuan.Data.Giangvien", "MaGvNavigation")
                        .WithMany("Phanbiens")
                        .HasForeignKey("MaGv")
                        .IsRequired()
                        .HasConstraintName("FK_PHANBIEN_GIANGVIEN");

                    b.Navigation("MaDtNavigation");

                    b.Navigation("MaGvNavigation");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Sinhvien", b =>
                {
                    b.HasOne("XuLyKhoaLuan.Data.Chuyennganh", "MaCnNavigation")
                        .WithMany("Sinhviens")
                        .HasForeignKey("MaCn")
                        .HasConstraintName("FK_SINHVIEN_CHUYENNGANH");

                    b.Navigation("MaCnNavigation");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Thamgia", b =>
                {
                    b.HasOne("XuLyKhoaLuan.Data.Sinhvien", "MaSvNavigation")
                        .WithMany("Thamgia")
                        .HasForeignKey("MaSv")
                        .IsRequired()
                        .HasConstraintName("FK_THAMGIA_SINHVIEN");

                    b.HasOne("XuLyKhoaLuan.Data.Dotdk", "Dotdk")
                        .WithMany("Thamgia")
                        .HasForeignKey("NamHoc", "Dot")
                        .IsRequired()
                        .HasConstraintName("FK_THAMGIA_DOTDK");

                    b.Navigation("Dotdk");

                    b.Navigation("MaSvNavigation");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Thamgiahd", b =>
                {
                    b.HasOne("XuLyKhoaLuan.Data.Giangvien", "MaGvNavigation")
                        .WithMany("Thamgiahds")
                        .HasForeignKey("MaGv")
                        .IsRequired()
                        .HasConstraintName("FK_THAMGIAHD_GIANGVIEN");

                    b.HasOne("XuLyKhoaLuan.Data.Hoidong", "MaHdNavigation")
                        .WithMany("Thamgiahds")
                        .HasForeignKey("MaHd")
                        .IsRequired()
                        .HasConstraintName("FK_THAMGIAHD_HOIDONG");

                    b.HasOne("XuLyKhoaLuan.Data.Vaitro", "MaVtNavigation")
                        .WithMany("Thamgiahds")
                        .HasForeignKey("MaVt")
                        .IsRequired()
                        .HasConstraintName("FK_THAMGIAHD_VAITRO");

                    b.Navigation("MaGvNavigation");

                    b.Navigation("MaHdNavigation");

                    b.Navigation("MaVtNavigation");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Thongbao", b =>
                {
                    b.HasOne("XuLyKhoaLuan.Data.Khoa", "MaKhoaNavigation")
                        .WithMany("Thongbaos")
                        .HasForeignKey("MaKhoa")
                        .HasConstraintName("FK_THONGBAO_KHOA");

                    b.Navigation("MaKhoaNavigation");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Truongbm", b =>
                {
                    b.HasOne("XuLyKhoaLuan.Data.Bomon", "MaBmNavigation")
                        .WithMany("Truongbms")
                        .HasForeignKey("MaBm")
                        .IsRequired()
                        .HasConstraintName("FK_TRUONGBM_BOMON");

                    b.HasOne("XuLyKhoaLuan.Data.Giangvien", "MaGvNavigation")
                        .WithMany("Truongbms")
                        .HasForeignKey("MaGv")
                        .IsRequired()
                        .HasConstraintName("FK_TRUONGBM_GIANGVIEN");

                    b.Navigation("MaBmNavigation");

                    b.Navigation("MaGvNavigation");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Truongkhoa", b =>
                {
                    b.HasOne("XuLyKhoaLuan.Data.Giangvien", "MaGvNavigation")
                        .WithMany("Truongkhoas")
                        .HasForeignKey("MaGv")
                        .IsRequired()
                        .HasConstraintName("FK_TRUONGKHOA_GIANGVIEN");

                    b.HasOne("XuLyKhoaLuan.Data.Khoa", "MaKhoaNavigation")
                        .WithMany("Truongkhoas")
                        .HasForeignKey("MaKhoa")
                        .IsRequired()
                        .HasConstraintName("FK_TRUONGKHOA_KHOA");

                    b.Navigation("MaGvNavigation");

                    b.Navigation("MaKhoaNavigation");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Xacnhan", b =>
                {
                    b.HasOne("XuLyKhoaLuan.Data.Detai", "MaDtNavigation")
                        .WithMany("Xacnhans")
                        .HasForeignKey("MaDt")
                        .IsRequired()
                        .HasConstraintName("FK_XACNHAN_DETAI");

                    b.HasOne("XuLyKhoaLuan.Data.Giangvien", "MaGvNavigation")
                        .WithMany("Xacnhans")
                        .HasForeignKey("MaGv")
                        .IsRequired()
                        .HasConstraintName("FK_XACNHAN_GIANGVIEN");

                    b.Navigation("MaDtNavigation");

                    b.Navigation("MaGvNavigation");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Bomon", b =>
                {
                    b.Navigation("Giangviens");

                    b.Navigation("Hoidongs");

                    b.Navigation("Kehoaches");

                    b.Navigation("Nhiemvus");

                    b.Navigation("Truongbms");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Chuyennganh", b =>
                {
                    b.Navigation("Sinhviens");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Congviec", b =>
                {
                    b.Navigation("Baocaos");

                    b.Navigation("Binhluans");

                    b.Navigation("Hdgopies");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Detai", b =>
                {
                    b.Navigation("Dangkies");

                    b.Navigation("Duyetdts");

                    b.Navigation("Hdphanbiens");

                    b.Navigation("Huongdans");

                    b.Navigation("Phanbiens");

                    b.Navigation("Xacnhans");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Dotdk", b =>
                {
                    b.Navigation("Thamgia");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Giangvien", b =>
                {
                    b.Navigation("Duyetdts");

                    b.Navigation("Huongdans");

                    b.Navigation("Nhiemvus");

                    b.Navigation("Phanbiens");

                    b.Navigation("Thamgiahds");

                    b.Navigation("Truongbms");

                    b.Navigation("Truongkhoas");

                    b.Navigation("Xacnhans");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Hdphanbien", b =>
                {
                    b.Navigation("Hdpbchams");

                    b.Navigation("Hdpbnhanxets");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Hoidong", b =>
                {
                    b.Navigation("Thamgiahds");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Huongdan", b =>
                {
                    b.Navigation("Congviecs");

                    b.Navigation("Hdcham")
                        .IsRequired();

                    b.Navigation("Hdgopies");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Khoa", b =>
                {
                    b.Navigation("Bomons");

                    b.Navigation("Chuyennganhs");

                    b.Navigation("Giaovus");

                    b.Navigation("Kehoaches");

                    b.Navigation("Thongbaos");

                    b.Navigation("Truongkhoas");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Nhom", b =>
                {
                    b.Navigation("Congviecs");

                    b.Navigation("Dangkies");

                    b.Navigation("Loimois");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Phanbien", b =>
                {
                    b.Navigation("Pbcham")
                        .IsRequired();

                    b.Navigation("Pbnhanxets");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Sinhvien", b =>
                {
                    b.Navigation("Nhoms");

                    b.Navigation("Thamgia");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Thamgia", b =>
                {
                    b.Navigation("Baocaos");

                    b.Navigation("Binhluans");

                    b.Navigation("Hdchams");

                    b.Navigation("Hdpbchams");

                    b.Navigation("Loimois");

                    b.Navigation("Pbchams");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Thamgiahd", b =>
                {
                    b.Navigation("Hdphanbiens");
                });

            modelBuilder.Entity("XuLyKhoaLuan.Data.Vaitro", b =>
                {
                    b.Navigation("Thamgiahds");
                });
#pragma warning restore 612, 618
        }
    }
}
